import Head from 'next/head'
import Calendar from '@/components/calendar'

export default function Home() {
  return (
    <>
      <Head>
        <title>Calendar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-5/6 mx-auto">
        <Calendar />
      </main>
    </>
  )
}
